### PR TITLE
Various fixes and improvements

### LINKED ISSUE #5: Properly handle requests to install a plugin that has already been installed
If an `eth_addPlugin_*` request is made for a plugin that has already been added, we need to handle it gracefully.

Likely we want to return a message or object to the requester.

A case to consider is whether the plugin code has been added, but the plugin is not "active". We perhaps need to show another permission request to run the plugin.

### LINKED ISSUE #68: Add method for getting permitted plugins
There's no dedicated way for domains to check if a plugin is installed _and_ permitted. We should add an external `wallet_` RPC method to check whether a plugin is installed, and potentially get metadata about e.g. the version and so on.

This suggestion did not originally contain the "permitted" condition. We should not let external domains poll for plugins without having permissions to them.

This method will either be an entirely new `wallet_getPlugins` RPC method or a modification of the soon-to-be-implemented `wallet_installPlugins` method.

### LINKED ISSUE #99: Possible Memory Leak: Plugin Providers
We currently call `setupProvider` twice during the plugin installation flow, and I don’t see teardown code anywhere. Clearing plugin state probably isn’t enough.

`setupProvider` defined here: https://github.com/MetaMask/metamask-plugin-beta/blob/develop/app/scripts/metamask-controller.js#L1617-L1631

`setupProvider` called twice during plugin installation:
1. https://github.com/MetaMask/metamask-plugin-beta/blob/develop/app/scripts/controllers/plugins.js#L199
2. https://github.com/MetaMask/metamask-plugin-beta/blob/develop/app/scripts/controllers/permissions/permissions.js#L186

To properly do this teardown, we need some of the changes introduced in the `LoginPerSite` branch of the primary extension repository.

### LINKED ISSUE #138: Stop storing `approvedPermissions` in plugin controller
Currently, the plugin controller stores a plugin's `approvedPermissions` in its own state. The permissions controller should _always_ be the single source of truth for the current state of permissions. The plugin controller should query the permissions controller whenever it initializes plugins.

### PR DESCRIPTION
**Pull request by rekmarks**
Fixes #5, Fixes #68, Fixes #99, Fixes #138

### Changes in Detail

- Add `wallet_getPlugins` RPC method
  - This returns metadata about permitted plugins to the caller
  - Indicates whether plugins are installed or not
- `PermissionsController`
  - _Do not reinstall plugins if they're already installed_
    - _At this point in beta, plugins should just be removed using the buttons we expose before reinstalling them_
  - New methods: `getPermittedPlugins`, `clearDomainMetadata`
  - Improve section demarcation/commenting
- `PluginsController`
  - _Add teardown for plugin `onMetaMaskEvent` listeners_
    - _We weren't removing these event listeners previously!_
    - _Added new methods:_ `_removeAllMetaMaskEventListeners`, `_removeAllMetaMaskEventListeners`
    - _Extensively modified:_ `_createMetaMaskEventListener`, `_generateMetaMaskListenerMethodsMap`, `_eventEmitterToListenerMap`
  - _Add doc comments for all but the most trivial internal methods_
    - _This is where much/most of the diff comes from_
  - Stop storing `plugin.approvedPermissions`
    - Always get current plugin permissions from `PermissionsController`
    - Does not affect `initialPermissions`
  - New method: `getSerializable` for getting plugins without getting e.g. their source code
- Tear down plugin providers
  - See method `closeAllConnections` in `metamask-controller.js` and its use in `PluginsController`
- Miscellaneous
  - Return `userRejectedRequest` error from `wallet_enable` if no permissions were granted
  - Rename `siteMetadata` to `domainMetadata` everywhere
    - To reflect that it can refer to not just sites, but also plugins, and who knows what else in the future

### CODE REVIEW

File: app/scripts/controllers/permissions/index.js [hunk 1]
```diff
@@ -413,9 +438,6 @@ class PermissionsController {
     await Promise.all(Object.keys(requestedPlugins).map(async pluginName => {
 
       const permissionName = PLUGIN_PREFIX + pluginName
-      result[pluginName] = {
```
Comment (rekmarks) [inline app/scripts/controllers/permissions/index.js]: Key renamed `permissionName` and now populated in `processRequestedPlugin`.

File: app/scripts/controllers/permissions/index.js [hunk 2]
```diff
@@ -413,9 +438,6 @@ class PermissionsController {
...
-        permission: permissionName,
```
Comment (rekmarks) [inline app/scripts/controllers/permissions/index.js:417]: Key renamed `permissionName` and now populated in `processRequestedPlugin`.

File: app/scripts/controllers/permissions/index.js [hunk 3]
```diff
@@ -73,6 +86,7 @@ class PermissionsController {
       getAccounts: this.getAccounts.bind(this, origin),
       requestPermissions: this._requestPermissions.bind(this, origin),
       installPlugins: this.installPlugins.bind(this),
+      getPlugins: this.getPermittedPlugins.bind(this),
```
Comment (danfinlay) [inline app/scripts/controllers/permissions/index.js]: You probably meant to also bind the `origin` here, as to not trust the method caller to provide its origin?

File: app/scripts/controllers/permissions/index.js (hunk 2 above)
Comment (danfinlay) [reply app/scripts/controllers/permissions/index.js:417]: Ok, I'm fine with this, but in general I lean towards minimizing api-surface changes that don't add behavioral changes, just to minimize context switching for returning readers and module consumers.

File: app/scripts/controllers/permissions/index.js [hunk 4]
```diff
@@ -428,15 +467,41 @@ class PermissionsController {
...
+  /**
+   * Get the permitted plugins for the given origin, by plugin name.
+   * Recall that plugin names !== permission names.
+   *
+   * @param {string} origin - The origin to get the permitted plugins for.
+   */
+  getPermittedPlugins (origin) {
+
+    return this.getPermissionsFor(origin).reduce(
+      (acc, p) => {
```
Comment (danfinlay) [inline app/scripts/controllers/permissions/index.js]: I know Aaron would make a firm stance against single-letter variables. We should probably add it to the linter, because I know it's a custom that he prefers to enforce. I think there's a good reason: They're hard to quickly text-search for.

File: app/scripts/controllers/permissions/methodMiddleware.js [hunk 5]
```diff
@@ -91,6 +91,12 @@ module.exports = function createRequestMiddleware ({
         }
         return
 
+      // returns permitted and installed plugins to the caller
+      case 'wallet_getPlugins':
+
+        res.result = getPlugins(req.origin)
```
Comment (danfinlay) [inline app/scripts/controllers/permissions/methodMiddleware.js]: Oh, I see you're passing in `origin` here. I guess this is basically equivalent. I wouldn't block over that other note, although it seems like it's generally safer to attenuate a function before passing it somewhere else.

File: app/scripts/controllers/permissions/methodMiddleware.js [hunk 6]
```diff
@@ -149,15 +153,15 @@ module.exports = function createRequestMiddleware ({
...
+          // so we're filtering out non-plugin and preexisting permissions
           .filter(p => (
             p.parentCapability.startsWith(PLUGIN_PREFIX) &&
             p.parentCapability in requestedPermissions
           ))
-          .map(p => p.parentCapability.replace(pluginPrefixRegex, ''))
+          // convert from namespaced permissions to plugin names
+          .map(p => p.parentCapability.replace(PLUGIN_PREFIX_REGEX, ''))
           .reduce((acc, pluginName) => {
             acc[pluginName] = {}
```
Comment (danfinlay) [inline app/scripts/controllers/permissions/methodMiddleware.js:173]: If the plugin permissions included some options, would we want to preserve them here, rather than initializing a new object? Not a blocker, since we don't yet have plugin install options.

File: app/scripts/controllers/permissions/restrictedMethods.js [hunk 7]
```diff
@@ -146,7 +146,7 @@ function getExternalRestrictedMethods (permissionsController) {
           // Here is where we would invoke the message on that plugin iff possible.
           const handler = permissionsController.pluginsController.rpcMessageHandlers.get(origin)
           if (!handler) {
-            res.error = ethErrors.methodNotFound({
+            res.error = ethErrors.rpc.methodNotFound({
```
Comment (danfinlay) [inline app/scripts/controllers/permissions/restrictedMethods.js:149]: I've been catching these missing `.rpc` instances around the code, too. Just so I know, what was the motivation to change this API?

I'm pretty sure if this was a mono-repo (rpc errors and our other repos), we could use IDE tools like "refactor" to make sure we're changing all uses of a method everywhere at once, but since we don't do that, changing APIs is still scary and kinda dangerous if not done methodically.

File: app/scripts/controllers/plugins.js [hunk 8]
```diff
@@ -1,10 +1,19 @@
...
+const { ethErrors, serializeError } = require('eth-json-rpc-errors')
+
 const {
   pluginRestrictedMethodDescriptions,
 } = require('./permissions/restrictedMethods')
-const { ethErrors } = require('eth-json-rpc-errors')
+const { PLUGIN_PREFIX } = require('./permissions/enums')
+
+const ENUMS = {
+  excludeFromSerialization: [
```
Comment (danfinlay) [inline app/scripts/controllers/plugins.js]: This is a nice addition. I suspect a permit-list would be slightly easier to securely maintain, since we couldn't forget forget to serialize some functional data, but we could easily forget to remove some sensitive data.

File: app/scripts/controllers/plugins.js [hunk 9]
```diff
@@ -21,6 +30,12 @@ const SES = (
     : require('ses')
 )
 
+const getGetDomainMetadataFunction = (pluginName) => {
```
Comment (danfinlay) [inline app/scripts/controllers/plugins.js]: `getGet` looks like a typo.

Comment (danfinlay) [reply app/scripts/controllers/plugins.js]: I guess it isn't? I guess this really is a getter for a getter function, so maybe that's fine, I wouldn't block over it, just saying.

File: app/scripts/controllers/plugins.js [hunk 10]
```diff
@@ -49,43 +64,79 @@ class PluginsController extends EventEmitter {
...
-      const ethereumProvider = this.setupProvider({ hostname: pluginName }, async () => {
-        return { name: pluginName }
-      }, true)
+      const approvedPermissions = this._getPermissionsFor(pluginName).map(
+        perm => perm.parentCapability
+      )
+
+      const ethereumProvider = this.setupProvider(
+        { hostname: pluginName },
+        getGetDomainMetadataFunction(pluginName),
```
Comment (danfinlay) [inline app/scripts/controllers/plugins.js]: Maybe I'd name it `createGetDomainMetadataFunction` or something, since this function doesn't exist yet, so it's not quite a getter? Avoids the redundancy, anyways..

File: app/scripts/controllers/plugins.js [hunk 11]
```diff
@@ -49,43 +64,79 @@ class PluginsController extends EventEmitter {
...
+   * the plugin sourceCode may be quite large.
+   */
   get (pluginName) {
     return this.store.getState().plugins[pluginName]
   }
 
+  /**
+   * Gets the plugin with the given name if it exists, excluding any
+   * non-serializable or expensive-to-serialize data.
+   */
```
Comment (danfinlay) [inline app/scripts/controllers/plugins.js:144]: I appreciate all the nice comments you've added in this PR.

File: app/scripts/controllers/plugins.js [hunk 12]
```diff
@@ -226,68 +286,61 @@ class PluginsController extends EventEmitter {
...
-    const pluginState = this.store.getState().plugins
-    const plugin = pluginState[pluginName]
-    const { sourceCode, initialPermissions } = plugin
-    const ethereumProvider = this.setupProvider({ hostname: pluginName }, async () => {
-      return {name: pluginName }
-    }, true)
+    return plugin
+  }
 
+  authorize (pluginName, ethereumProvider) {
```
Comment (danfinlay) [inline app/scripts/controllers/plugins.js:431]: Well now I'm spoiled and wish I had one of your nice comments on this one. I was lazy and left my plugin lifecycle comments at the top of the file.

**Review by danfinlay — APPROVED** [review]
Nice cleanup, lots of improvements, I don't think there are any blockers, but a few little discussion points worth reviewing.

File: app/scripts/controllers/permissions/index.js (hunk 4 above)
Comment (rekmarks) [reply app/scripts/controllers/permissions/index.js]: `p => perm`

File: app/scripts/controllers/permissions/methodMiddleware.js (hunk 5 above)
Comment (rekmarks) [reply app/scripts/controllers/permissions/methodMiddleware.js]: Yeah, the origin middleware at the top of the stack should take care of it, but there is as you point out no reason to not attenuate the function. Did the same for `installPlugins`!

File: app/scripts/controllers/permissions/index.js (hunk 3 above)
Comment (rekmarks) [reply app/scripts/controllers/permissions/index.js]: See: https://github.com/MetaMask/metamask-snaps-beta/pull/137#discussion_r359989304

File: app/scripts/controllers/plugins.js (hunk 10 above)
Comment (rekmarks) [reply app/scripts/controllers/plugins.js]: Yeah, that's much better!

File: app/scripts/controllers/plugins.js (hunk 8 above)
Comment (rekmarks) [reply app/scripts/controllers/plugins.js]: Changed to an `Object<string, boolean>` called `shouldSerialize`.

File: app/scripts/controllers/plugins.js (hunk 12 above)
Comment (rekmarks) [reply app/scripts/controllers/plugins.js:431]: Hah, this innocuous question really opened pandora's box. We didn't have teardown for plugin `onMetaMaskEvent` listeners! See updated description.

File: app/scripts/controllers/permissions/restrictedMethods.js (hunk 7 above)
Comment (rekmarks) [reply app/scripts/controllers/permissions/restrictedMethods.js:149]: I made the change a long time ago for `eth-json-rpc-errors@2.0.0`, because I thought mixing the kind of things we found in a particular level of the API namespace (in `<2.0.0`, i.e. JSON RPC errors directly under `rpcErrors` as well as the `eth` property, which had all the Ethereum Provider errors).

When I upgraded the module I made the changes everywhere, but I didn't communicate the change to you and others, and I think that's why we're finding these errors.

File: app/scripts/controllers/plugins.js [hunk 13]
```diff
@@ -363,45 +484,107 @@ class PluginsController extends EventEmitter {
...
+          throw new Error('Unknown event name.')
+        } else {
+          throw new Error('Unpermitted event name.')
+        }
+      }
+
+      // remove any existing listener
+      if (registeredListenersMap.has(eventName)) {
+        // call the stored removal function, it will be replaced later
+        registeredListenersMap.get(eventName)()
```
Comment (danfinlay) [inline app/scripts/controllers/plugins.js]: We probably want to rename this listeners map to indicate it's a map of removal functions.

**Review by danfinlay — APPROVED** [review]
